baseurl = "http://lashl.ee"
publishDir = "../lashlee.github.io"
title = "John's Blog"
author = "John Lashlee"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "John's Blog"

[[menu.main]]
    name = "Home"
    url = "http://www.lashl.ee"
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/lashlee"
    weight = 2
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/johnlashlee"
    weight = 3
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/johnlashlee"
    weight = 4
[[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 5
